### ISSUE TITLE
problem with moving the viewports on Mac OS X Yosemite (Knossos 4.1)

### ISSUE THREAD

**Issue by user1564** [knossos-project/knossos#100]
On MAC OS X Yosemite one can't see the buttons in the lower right corner of the viewports, although the option "show viewport decorations" is enabled. Although it is possible to scale the viewports by dragging a point somewhere in the lower right corner it is not possible to move the viewports by clicking CTRL while dragging (as it is explained in the documentation).

**Comment by Optiligence** [comment]
It’s `Ctrl`+`Alt`+`Mouse Left Drag` to move the viewports. (the docs are just wrong in this case)

That the buttons are not visible is an ongoing framework issue on Mac. 
The skeleton viewport has a context menu as a replacement via `Ctrl`+`Mouse Right Click`.

**Comment by Optiligence** [comment]
As explained somewhere in the docs, on Mac `Ctrl` is actually mapped to the `⌘`-Key, so it would be `⌘`+`Alt`+`left mouse drag`.
