### ISSUE TITLE
Make heidelbrain.org default host in task management

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#108]
n/t

**Comment by Optiligence** [comment]
Didn’t we remove this intentionally?

**Comment by fabiansvara** [comment]
Did we? Why? It causes a constant stream of e-mails.

**Comment by fabiansvara** [comment]
The only argument that I see is that it would be somewhat unaesthetic to users outside of our group. I do not see a real problem with it, though. It might be slightly nicer to leave the default empty, but have a drop-down pre-populated with heidelbrain.org.

**Comment by Optiligence** [comment]
apparently it was unintentional, it’s still set inside Knossos but after the widget is created
