### ISSUE TITLE
KNOSSOS crashes on Mac when trying to save segmentation

### ISSUE THREAD

**Issue by chbehrens** [knossos-project/knossos#111]
Makes saving volume segmentations impossible on Mac.

**Comment by Optiligence** [comment]
It seems to work for us, so please specify what you did exactly and check if your system doesn’t run out of memory.

**Comment by chbehrens** [comment]
Whenever I try to load or save a volume segmentation on Mac, KNOSSOS crashes. It's independent of the size of the segmentation and I do not run out of memory. Saving and loading skeletons is fine. Maybe it is a problem with the snappy compression since libsnappy runs in the thread that crashes. In 4.1 I have no problems saving segmentations.

**Comment by Optiligence** [comment]
Could you upload a stacktrace e.g. to http://pastebin.com/
There were no changes wrt snappy since v4.1, so i suspect it’s a deployment issue.

**Comment by chbehrens** [comment]
http://pastebin.com/PDeFieiS

**Comment by Optiligence** [comment]
The snappy library within the mac package was exchanged, can you please try it and report back?

**Comment by chbehrens** [comment]
Seems to work fine now
