### ISSUE TITLE
KNOSSOS crashes on startup if M too big for texture size

### ISSUE THREAD

**Issue by my-tien** [knossos-project/knossos#113]
In datasetloadwidget:

    if(state->M * state->cubeEdgeLength >= TEXTURE_EDGE_LEN) {
            qDebug() << "Please choose smaller values for M or N. Your choice exceeds the KNOSSOS texture size!";
        throw std::runtime_error("Please choose smaller values for M or N. Your choice exceeds the KNOSSOS texture size!");
    }

We should not crash, just load dataset with smaller M.

**Comment by Optiligence** [comment]
It should not be possible to select this. 
The upper limit was removed but readded in the past and is in place now. 
This does only happen when you specify a too high M in the cmdline. 
#97 would also overcome this

**Comment by Optiligence** [comment]
It’s just an assertion inside Knossos (whose existence is a good thing imo) and if you got there in the first place something is wrong.

**Comment by Optiligence** [comment]
#97 is fixed
