### ISSUE TITLE
There should only be a "What's next?" button in Task Management

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#12]
It is not necessary to have many buttons, only one is required - to check whether a task is in progress and either start a new one or continue work on the current one and to make a submission when currently working on a task.

**Comment by fabiansvara** [comment]
Not having this is actually a huge time-waster. Currently, when working on many tasks in sequence, you have to Submit, click OK, click start new task, click override. This could be just one click plus confirmation instead (with a separate button for doing a non-final submission). When working on reannotation tasks that are actually really short, this could actually explain complaints of tracers who think they are working more than Heidelbrain thinks.

**Comment by Optiligence** [comment]
One button would remove currently available functionality. ›Load last Submit‹ and ›Start new Task‹ are mutually exclusive and are therefore only available when a task is loaded or not respectively. ›Submit‹ is deactivated when no task is loaded (could also be hidden). 
The submit buttons currently require no confirmation (a submission does no harm). 
Is a confirmation wanted, only for the final submit, maybe? 
Is there anything else but the miserable layout which could be improved?

**Comment by fabiansvara** [comment]
What relevant functionality do you think we would lose by merging the "Load last Submit" and "Start New Task" buttons? The way I see it, you just want to linearly proceed along the Start Task -> Make submissions -> Make final submission -> Start Next task cycle, which would be covered by one button, one checkbox for final submission and one confirmation dialog for final submission.

**Comment by Optiligence** [comment]
These 2 Buttons are already merged. 
But you need to be able to load submits as well as saving them at the same time. 
One could use a checkbox instead of a ›submit final‹ button, but then an extra confirmation would be a bit redundant.

**Comment by fabiansvara** [comment]
Why do you need to be able to do that at the same time?

**Comment by fabiansvara** [comment]
One unrelated thing that could be improved would be naming of the autosaves based on the task name, with special labeling of the autosaves corresponding to submits, i.e. for every submit there should be an automatically saved file called something along the lines of task_category_task_name-submit-timestamp.k.zip

**Comment by Optiligence** [comment]
#42 would also be nice but has nothing to do with this issue

**Comment by Optiligence** [comment]
Anything to be improved, except the layout?
