### ISSUE TITLE
Setting to disable notification after connected components in which tree component was extract

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#131]

**Comment by Optiligence** [comment]
Do we wan to establish some modifier key, which skips message boxes when selecting an option?

**Comment by jmrk84** [comment]
I don't like too many modifier keys that need to be remembered. A better option would be IMO to have a checkbox "Do not show again" and some mechanism that allows a reset of this checkbox

**Comment by Optiligence** [comment]
You could reset the settings to get it back. 
One could also reset it on every start of Knossos.
