### ISSUE TITLE
SkeletonVP state doesn't work (reading from file)

### ISSUE THREAD

**Issue by al3xst** [knossos-project/knossos#134]
Loading the 300.k.zip annotation, the skeleton viewport looks wrong:

![screenshot from 2015-03-24 18 25 42](https://cloud.githubusercontent.com/assets/1877167/6808309/a4b8f10e-d253-11e4-9e99-827337752300.png)

"Reset" fixes the issue.

**Comment by Optiligence** [comment]
This seems to be a more serious issue as it sometimes omits rendering half of the skeleton until reset’. 
If we don’t fix this properly until the next release i’d opt for ignoring the value from the annotation file.

**Comment by Optiligence** [comment]
not used, for now
