### ISSUE TITLE
static python (windows)

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#135]
As it will now probably work out with qtall and static, maybe someone can verify if it is possible to link to python statically while retaining the current intuitive/flexible functionality. 
(i.e. using installed packages of the system-wide installed python distribution)

**Comment by jmrk84** [comment]
Looks like everything works great on windows 7 64 bit.

**Comment by Optiligence** [comment]
this issue was about something else, but we discussed it yesterday anyway
