### ISSUE TITLE
Selecting merge on file load overrides instead

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#140]
This is slightly mysterious since I believe I have seen this work in the past in this version, but it is currently reproducible. Tried with drag'n'drop loading and loading through the menu bar.

When loading a file (containing multiple trees, currently unsure whether this is essential) when another annotation is loaded already, Knossos gives the option to either merge or override. Override works as expected, but Merge has the same effect as override. When trying to load the same file again afterwards and selecting Merge, Knossos asks whether one wants to proceed even though there are unsaved changes. When selecting "Abandon changes", the effect is override-loading. When clicking cancel, the effect is merge-loading.

**Comment by fabiansvara** [comment]
Happens in 4.1.1.

**Comment by Optiligence** [comment]
#127 is the reason for this. The unsaved changes is from datase load.
