### ISSUE TITLE
Segmentation fault after merge trees

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#144]
Does not happen always, but this is a major issue.

**Comment by Optiligence** [comment]
Especially when it’s not reproducable, it would be nice to have a few more infos about the circumstances. Did it crash during the merge operation, afterwards when clicking something? How many trees and nodes where there? Was something the first or last entry before or afterwards? What about the ids? Did something else look suspicious?

**Comment by jmrk84** [comment]
I think it was exactly during the merge operation. There were many trees, and it was a small tree that was merged into a large one (the small part was splitted away from another tree before).

**Comment by jmrk84** [comment]
We will probably get a lot of feedback on this very soon (this is the basic operation of one of the new tasks that are currently distributed)

**Comment by Optiligence** [comment]
Is reproducable
