### ISSUE TITLE
Multiple node selection is broken

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#148]
Select several nodes using Ctrl+Left-Click in the XY viewport,
then de-select and select again, just play around with it.
Soon you will notice the actual node-selection in the annotation
widget (which is also reflected from/to the internal selectedNodes
list in skeletonState) is out-of-sync from the nodes marked green
in the viewport. They widget ones are less, they most notably exclude
(at least?) one node. Selecting this node in the annotation widget
syncs the viewport back to the annotation selection state.

Forget the description, just check it yourself, it's broken.

**Comment by Optiligence** [comment]
#22 :p

**Comment by orenshatz** [comment]
? :-0

**Comment by Optiligence** [comment]
As i said on another issue: for the sanity of the implementor — #22

**Comment by orenshatz** [comment]
What is for the sanity, that the user selects nodes and has no clue why it's out of sync?

**Comment by orenshatz** [comment]
Or that a single issue concentrates all the bugs in the annotation/tree context?

**Comment by Optiligence** [comment]
it had in fact nothing to do with the annotation widget
