### ISSUE TITLE
Display warning in title-bar when Knossos is not auto-saving

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#149]
n/t

**Comment by Optiligence** [comment]
Wouldn’t autosave state in general be useful to know?

**Comment by fabiansvara** [comment]
Yes, but accidentally auto-saving is not a problem, while accidentally not auto-saving could be. It seems more aesthetic to not clutter the title-bar in that case...

**Comment by Optiligence** [comment]
Well as a dev i hate autosave^^
