### ISSUE TITLE
QT concurrent run does not allow setting of thread priority / cancelation

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#152]
Especially the thread priority leads to the issue that decompression slows down the browsing experience. This can be prevented by reducing the number of threads (always leaving one core for the viewer), at the cost of a slower decompression.

**Comment by Optiligence** [comment]
Although the pooled threads try to lower their priority, I’m convinced this wouldn’t be an issue anyway. 
The problem is reslicing due to compression finished signals.
