### ISSUE TITLE
Node inclusive/toggle selection

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#159]
Currently Ctrl+Left-Mouse-Drag selects the underlying nodes, even when they are already selected.
This is counter-intuitive at least for me as a windows user, who expects this to actually toggle the
selection.
I propose Ctrl+Drag to toggle selection, and another modifier - the intuitive windows one is Shift+Drag -
to inclusively select.

**Comment by jmrk84** [comment]
I support your proposal

**Comment by Optiligence** [comment]
There is a downside though. 
Whereas selecting with `shift` was selecting on mouse down before, it is now also only selecting after releasing the mouse button. You start a selection rectangle when `ctrl` or `shift` is detected while the left mouse button is pressed but which type of selection is used is determined when you release the mouse button. If none of the 2 keys is pressed (was released while still holding the mouse button) the selection remains unaffected. One could default to one of both here, idk.  
I’m starting to think that it’d be nice to switch between drag and selection mode instead.
