### ISSUE TITLE
Task management sometimes does not submit

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#160]
In the current master, the submit buttons sometimes have no effect except for unloading the current annotation. The status of the task on Heidelbrain remains unchanged and the task management widget still displays the task as active. I will try to nail down more precisely when this happens, but currently can't reproduce. The first time I observed it it happened directly after starting Knossos, with very little user activity.

**Comment by Optiligence** [comment]
Is this with the changes from yesterday or not?

**Comment by fabiansvara** [comment]
Yes it is, there's still something wrong.

**Comment by Optiligence** [comment]
Unloading the current annotation only happens on a final submit and since yesterday also only when it was successful. But i will also try to figure out if something is wrong from within the code.

**Comment by Optiligence** [comment]
@fabiansvara I did not intentionally fix anything, but the code was replaced nearly completely, so the course of action should be reevaluation of this issue.
