### ISSUE TITLE
Segmentation mode does not accept user click actions anymore

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#162]
Reproducable with a kzip I have here. All segmentation actions in the viewports (paint / erase / merge) are either severely broken or have no more effect. This is pretty bad, restarting does not help with the same kzip.

**Comment by jmrk84** [comment]
No reproducable on different machine...

**Comment by Optiligence** [comment]
And what about the exact machine? 
Install team viewer and let us examine when it happens…
