### ISSUE TITLE
Can't minimize knossos on Linux

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#165]
When minimizing the current master, it maximizes itself again instantly.

**Comment by Optiligence** [comment]
Do you have any dialogs open?

**Comment by fabiansvara** [comment]
Yes, sure

**Comment by Optiligence** [comment]
I think it has to do with the fact, that the dialog windows want to stay on top of all windows. 
It doesn’t happen when all dialog windows are closed.
