### ISSUE TITLE
autosave indicator in the statusbar instead?

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#181]
The titlebar is already bloated with the filename. 
Wouldn’t it fit better aside the save state indicator in the lower right more?

**Comment by Optiligence** [comment]
@fabiansvara question was for you in particular, because you explicitly stated the titlebar in the original issue.

**Comment by fabiansvara** [comment]
I think this is an important safety feature, thus should be as obvious as possible. Status bar would be too inconspicuous IMO.

**Comment by Optiligence** [comment]
Is that really the case?
![screenshot from 2015-04-22 19-33-39](https://cloud.githubusercontent.com/assets/1899299/7280928/8bfdda8c-e926-11e4-80b7-24f1d3b604a4.png)

**Comment by Optiligence** [comment]
What about both?

**Comment by fabiansvara** [comment]
In your example it makes no sense to put it in the title bar indeed, but that's mostly because the absolute path to the file is being displayed. Anyway, I think status bar and highlighted in some way (bold or red) would be a good solution.

**Comment by Optiligence** [comment]
Can we settle on »when working on a task«? 
I’d rather not have a constant red thing in the statusbar. 
One could also add it to the task management.
