### ISSUE TITLE
White viewports (Remote Desktop)

### ISSUE THREAD

**Issue by chbehrens** [knossos-project/knossos#185]
Running Knossos under Win server 2008 the viewports show only blank white space instead of the raw data (dataset seems to be loaded). Skeletons are displayed correctly as well as dataset boundaries, volume segmentation is not shown. Maybe some rendering problem? (Already checked the graphics driver, it is the most recent one, but the graphics card is older, only supports OpenGL 3)

**Comment by Optiligence** [comment]
We are aware of this problem. 
When encountered we were always able to find a newer graphics driver which didn’t exhibit this issue. 
#97 would also workaround this

**Comment by chbehrens** [comment]
Since there seems to be no newer graphics driver, any chance to see a fix/workaround for this problem in near future?

**Comment by Optiligence** [comment]
Well #97 is expected to be fixed in the near future. Then again, as a preliminary workaround, we restrict some of Knossos’ functionality again in [the current release](https://github.com/knossos-project/knossos/releases/tag/v4.1.2). 
Just for reference: could you name the exact graphics card model?

**Comment by chbehrens** [comment]
NVIDIA GeForce GT 220

**Comment by Optiligence** [comment]
The most recent driver [only 2 months old](http://www.nvidia.de/download/driverResults.aspx/82603/de) and the card supports 8k textures. 
I’m pretty sure that this works and its only the basic Microsoft Drivers with their poor OpenGL Support which could be that bad to show white viewports.  
Do you have this driver installed? And if not, can you please test 4.1.1 with it again?

**Comment by chbehrens** [comment]
Ok, I think I got the problem. I have that driver installed, however I have only remote access to that machine. Hence, I guess the problem comes from the remote desktop connection which doesn't support proper OpenGL hardware acceleration. Sorry that I didn't mention the remote connection before.

**Comment by Optiligence** [comment]
Hm ok, interesting. 
Remote Desktop usually should not restrict rendering. 
Does it work with 4.1.2?

**Comment by jmrk84** [comment]
You can try switching to a screen grabber remote desktop app like teamviewer. RDP messes with the opengl backend, I've noticed that for other programs. Upgrading RDP to new version might also help, MS recently improved RDP a lot.

**Comment by chbehrens** [comment]
Both 4.1.2 and 4.1.1 were fully function when started locally with a screen connected to the workstation. Via remote desktop, I wasn't able to start 4.1.2 at all, it just crashed. I found an update for RDP, but won't be able to test it right now since I can't restart the workstation immediately.

**Comment by Optiligence** [comment]
Does it work for you now?

**Comment by chbehrens** [comment]
Unfortunately not since there is no update of the host component of the RDP for windows server 2008. So windows server 2008 sticks to RDP 7.1. I will check within the next days whether I can use a different remote desktop app or set Knossos up on a different machine with a different OS.

**Comment by Optiligence** [comment]
I think there is nothing we can do to help if something interferes with the rendering, so i’m closing this.
