### ISSUE TITLE
Branch managing in volume merge / split mode

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#194]
.... currently non-existing. Now that it is actually used, we need this urgently. A simple solution would be to carry over the skeleton branch management on the same key presses but with slightly different actions:
1) The user holds a modifier key (eg 'b') and then clicks in one of the view ports, a branch node is created and pushed onto the stack. This happens only when in merge mode.
2) 'j' brings the user back as before and deletes the node automatically

**Comment by fabiansvara** [comment]
... we can actually use skeleton branchpoints as temporary workaround.

**Comment by jmrk84** [comment]
Yes, this was the idea. 'b' and click creates a skeleton node + branch tag on it.

**Comment by Optiligence** [comment]
The question is, if it’s not a better idea to use a button (i.e. middle mouse) instead of a »mode«.

**Comment by Optiligence** [comment]
superseded by #199
