### ISSUE TITLE
Arbitrary mode idle cpu usage

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#206]
Whereas rendering takes 5-8% CPU on my machine in ortho mode, it takes 25%, namely the entire core (and responds sluggishly, so this must be a bottleneck) in arb mode. I would guess the blame is not on inefficient arbitrary rendering, because there should not be a special case render, but rather on the legacy constant-reslice code that was not adjusted - like the ortho - to only reslice when necessary.

**Comment by Optiligence** [comment]
Its reslicing everytime, yes, bacause changing the coordinate in arbitrary mode requires reslicing every viewport. Regarfless of that, arb segmentation is slow anyway, it’s just a fallback mode for the upcoming gpu slicing.

**Comment by orenshatz** [comment]
If we don't reslice when the user's not moving in ortho, we should also not reslice when the user's not moving in arb.

**Comment by Optiligence** [comment]
It doesn’t change the input lag. But i will adress this anyway.

**Comment by orenshatz** [comment]
What doesn't change which input lag?
