### ISSUE TITLE
Undocked viewports of arbitrary aspect ratio lose track of the brush

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#210]
Undock a viewport, resize to a height twice as width, and select segmentation mode, the brush cross-hair lags behind the circle.

**Comment by Optiligence** [comment]
#211

**Comment by orenshatz** [comment]
No real association to 210, we want it to work regardlessly of default aspect.

**Comment by Optiligence** [comment]
well, do we?

**Comment by orenshatz** [comment]
I think we do. Unless we disable the brush until the aspect ratio is fixed.

**Comment by Optiligence** [comment]
placing nodes also doesn’t work

**Comment by orenshatz** [comment]
worked for me. will check again later.
