### ISSUE TITLE
Multiple node selection in undocked VPs with wrong aspect ratio broken

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#217]
Probably essentially the same as #210

**Comment by orenshatz** [comment]
Norbert reported node placement error. I also see this.
But for me multiple selection actually works.

**Comment by fabiansvara** [comment]
Strange, this is actually easily reproduced for me. The selection rectangle is offset from the cursor.

**Comment by orenshatz** [comment]
I don't see a selection rectangle, I ctrl+click multiple times.
So it seems that everything having to do with selection by an area (brush, rectangle) is broken.

**Comment by Optiligence** [comment]
placing nodes has nothing to do with an area and also doesn’t work

**Comment by orenshatz** [comment]
Correct, to be precise it's about the cross-hair, which is used for selections and for node placement, but it not used for (iterative) single-node selection.
