### ISSUE TITLE
deb pkg: vp::initgl for first vp crashes on ivybridge laptop with ubuntu 14.04

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#223]
the driver should support enough functionality
idk if it has to do with some incompatible library we ship
but it crashes within knossos code, so it’s accessing an invalid variable

**Comment by orenshatz** [comment]
has to do with opengl instead of gl widget?

**Comment by Optiligence** [comment]
that’s not even uploaded yet
this is for debian package of the last release

**Comment by Optiligence** [comment]
deb pkg seems to work nearly nowhere anyway…
