### ISSUE TITLE
Widgets do not regain focus with knossos

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#226]
If I currently do something in annotation widget and then Alt+Tab to Firefox and then back to knossos,
one of the viewports no has focus.
This is bad not only because the user wants to continue working in the widget, but also since
hot viewport keys can accidently lead to irreversible errors in such condition, when the user
doesn't expect a key to be captured by the viewport.

**Comment by Optiligence** [comment]
I couldn’t any application which implements focus regain for child windows.

**Comment by orenshatz** [comment]
That's true, e.g the Help->About window in Firefox doesn't regain.
But for plugin windows it may be more important than for native knossos widgets,
since in many cases the plugin window would be the main work context rather than the viewport.

**Comment by Optiligence** [comment]
If a plugin wants focus, it can request it itself.
