### ISSUE TITLE
Status bar border

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#229]
Currently the status bar is not bordered, it's hard to tell it's there when there's no status present (which is the case until the first save-as).

**Comment by Optiligence** [comment]
depends on the system theme

**Comment by orenshatz** [comment]
For me in windows it's invisible, while Wordpad's status bar is visible nevertheless, so there should be some robust way to make it visible.

**Comment by Optiligence** [comment]
if we want to change something i think it should be the working area i.e. the centralWidget which contains the viewports

**Comment by orenshatz** [comment]
I'm not sure about implementation, I'm only saying the current look on my windows is less than ideal.
![border](https://cloud.githubusercontent.com/assets/7572520/7681223/a9d14312-fd6e-11e4-9046-7ba4d6740ce8.jpg)
