### ISSUE TITLE
Too much horizontal space on mobile website

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#234]
... this happens on the stock browser on Android 4.3 (at least). It should not be possible to scroll to the side when there is nothing there to be displayed.

**Comment by Eroica** [comment]
To be exact, there was something to see--a really long button!
![bildschirmfoto 2015-05-19 um 18 13 57](https://cloud.githubusercontent.com/assets/1134290/7708021/4974d11a-fe53-11e4-8bd6-f75631a86508.png)
I will fix the navigation bar in another commit.
