### ISSUE TITLE
Comment highlighting issues

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#242]
There are reports from tracers that comment highlighting does not always work as expected (node color and size are not adjusted). I believe I have also seen this before, but can't reproduce. This bug is to serve as a reminder to pay close attention to that feature and hopefully find a way to reproduce incorrect behavior.

**Comment by orenshatz** [comment]
Actually now with python it should be easier to reproduce such problems.
All operations can be scripted to be randomly carried out at random, while taking screen shots
in between into a z-stack in a TIFF (using Python Imaging Library), then going over the stack
in ImageJ. Super easy.

**Comment by orenshatz** [comment]
That's actually true for unit-testing in general, as long as functions are interfaced to python, and the result can be observed or is interfaced too.

**Comment by jmrk84** [comment]
Ahhh... I should look more at already exisiting issues ;-)

**Comment by my-tien** [comment]
The issue occured whenever the first shortcut F1 was empty. It always matched, so that susequent shortcuts were not tested.
