### ISSUE TITLE
Loader counter/isActive

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#243]
We need (soon) some flag (NOT only an event) that indicates whether the loader is currently loading something.
The current code is a mixture of flows, callback lambdas and concurrency, so it's better that whoever wrote it would take care of it.

**Comment by Optiligence** [comment]
`Loader::Controller` now offers an `isFinished` function (which ensures safety of cube operations in the main thread) as well as a `progress` signal and the `refCountChange` with the increment bool every time a download is dispatched, was canceled or a decompression finished. 
I’m also thinking of replacing the progress count with a percentage `float` in the future.
