### ISSUE TITLE
Simple Tracing violated by temporary deactivation

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#245]
1. Deactivate simple tracing
2. Switch to unlinked node placement
3. Activate simple tracing
4. Node placement is still unlinked

**Comment by Optiligence** [comment]
disabling the 2 restricted options would automatically activate linked nodes
it wasn’t done, so you can still click it and get the msg box

**Comment by orenshatz** [comment]
I'm not sure what you mean, bottom line, the select option should be invalid in simple mode.
