### ISSUE TITLE
snappy cubes eventually lead to no slots

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#246]
see log.txt in slack channel github

**Comment by Optiligence** [comment]
I just want to say, that the log really didn’t help at all. 
It would’ve been nice if you’d at least mentioned what you did and what you thought the issue was.

**Comment by orenshatz** [comment]
I did nothing special, I just used knossos to browse the dataset.
Perhaps I should have noticed that I used knossos normally.

**Comment by orenshatz** [comment]
By the way, if the log wasn't helpful, I'm not sure why you renamed the bug to a snappy issue.

**Comment by Optiligence** [comment]
with custom generated overlay, else this wouldnt’ve happened (i strongly assume so)

**Comment by Optiligence** [comment]
running downloads/decompressions are still a problem

**Comment by orenshatz** [comment]
Custom generated overlay is essentially standard knossos usage nowadays, it wasn't a very rare sequence of keystorkes and mouse events that led to this bug.
Anyway next time I will skip on attaching the log when I don't have complementary insights.
