### ISSUE TITLE
k.zip cannot be opened in mac os 10.9.5 with release 4.1.2

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#258]
Drag and drop does not work and Load annotation -> select file -> open goes into the "zip folder". This renders the mac version unusable.

**Comment by Optiligence** [comment]
I think you will still be able to select the `*.zip` via i.e. the context menu. 
No clue why drag’n’drop shouldn’t work.

**Comment by jmrk84** [comment]
Not sure exactly what you mean... in the context menu there is only "open" and this opens the "folder"

**Comment by Optiligence** [comment]
Does `*.nml` work in both?

**Comment by jmrk84** [comment]
I cannot test, this is a tracer bug report.

**Comment by Eroica** [comment]
Closing because the "bug" was probably only Safari automatically extracting the Zip archive.
