### ISSUE TITLE
Right click in "Load annotation" on kzip on mac segfaults knossos

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#259]

**Comment by Optiligence** [comment]
Within the file open dialog?

**Comment by jmrk84** [comment]
Yes

**Comment by Optiligence** [comment]
Doesn’t sound like something we can do much about. 
May have to do with the fact that the binary was built on 10.10.

**Comment by jmrk84** [comment]
I'm actually also more worried about the other issue ;)

**Comment by jmrk84** [comment]
Could somebody test this on mac 10.10 to see whether the behavior is the same with a *.k.zip. I really start regretting that we didn't name it .kzip

**Comment by Optiligence** [comment]
Mac is stubborn with custom extensions in general.

**Comment by Optiligence** [comment]
Deployment issue
