### ISSUE TITLE
Invisible Trees after Annotation Merge

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#26]
Annotate a tree at a certain position and save into file number 1.
Clear skeleton or restart a fresh knossos.
Annotate again another tree at the same position and save into file number 2.
Load file number 1, chose "Merge".
Now switch between the two trees (one from each file) by clicking nodes in the annotation widget.
Upon clicking a node from one tree, both trees are shown - as they should.
But clicking a node from the other tree shown only this one, while the other doesn't show at all.

**Comment by Optiligence** [comment]
>Then I will try again.

Did you?

**Comment by Optiligence** [comment]
not reproducible anymore
