### ISSUE TITLE
Mac Knossos 4.1.2 won't open

### ISSUE THREAD

**Issue by roblasher** [knossos-project/knossos#261]
Computer and OS: iMac with Intel 3.5GHz core i7 and 32 GB RAM running 10.10.4
After unzipping the app, and placing it into the applications folder, opening Knossos 4.1.2 results in an error saying that the app is incomplete or damaged. Any suggestions for fixing this problem. Thank you.

Robert Lasher roblasher@comcast.net or rob.lasher@ucdenver.edu

**Comment by Optiligence** [comment]
You can try one of the things from [this question](http://apple.stackexchange.com/questions/58050/damaged-and-cant-be-open-app-error-message). 
If you are able to resolve it please let us know. 
We will also look into why this could happen.

**Comment by Optiligence** [comment]
I’m also not sure that you are supposed to put it into the `Applications` folder. I think it should work if you just double click the extracted `.app`file.

**Comment by roblasher** [comment]
The app gives the same error (see below) no matter where it is located. This is not the same message that one gets when trying to open an app that is protected by gatekeeper. Turing off gatekeeper makes no difference. If I examine the package contents, I see another app inside called Knossos.app (see second screenshot). This app will open anywhere, but crashes after about 10 seconds. I am wondering if something in the latest update for Yosemite (10.10.4) is causing the problem or another extension that I have. I will try to open the app after dong a ‘Safe’ boot to see if that works. Rob Lasher

**Comment by Optiligence** [comment]
Unfortunately there are no screenshots attached. 
When I examine the package, I only see one `knossos.app`. 
The safe mode may not provide enough graphics capability for KNOSSOS to successfully start. 

Does this only happen with the newest Knossos version or also with previous ones? 
Did it work on your system before?

**Comment by Eroica** [comment]
Unfortunately, I can't reproduce this issue on my Mac running OS X 10.4. I just re-downloaded the KNOSSOS Zip file from our website http://www.knossostool.org, and it un-archives and opens without any problems.

I'm sorry if this sounds repetitive, but could you re-download the Zip archive as well and provide us with some screenshots if the problem still persists?

**Comment by roblasher** [comment]
I am not sure why the screenshots did not show up as they were in the email message.  In any case, after doing a safe boot, the app within the package (KNOSSOS.app) did open and did not crash. I got the same error with the unzipped file. All versions from 4.1 up give the same error message.  However, version 4.0.1 does open and does not crash. Its icon has the same appearance as that of the app inside the package in the later versions. Whatever process that makes the package containing the KNOSSOS.app seems to be causing the problem. I also may have an extension that is interfering.

**Comment by roblasher** [comment]
I think I may have solved the problem. The program I was using originally to unzip the file (the unarchiever.app) was corrupting the file. Opening with the Achieve Utility app resulted in a working app. If I have any more problems I will let you know.  Thank you for your comments.  Rob Lasher

**Comment by Eroica** [comment]
Alright, we are glad that you could solve this issue! We'll keep an eye out on possible bugs on our side that make our package unworkable with Unarchiver.app. Thanks for letting us know!
