### ISSUE TITLE
Task name field in NML / k.zip.

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#262]
Should be set by task management widget and checked by heidelbrain on submit. It has happened that users thought starting a new task had failed, then re-submitted the (supposed) previous task for the new active task accidentally.

**Comment by fabiansvara** [comment]
(this is better solved on the server side)

**Comment by Optiligence** [comment]
How do you want to solve that? 
Unknown nml tags are just skipped by knossos.

**Comment by fabiansvara** [comment]
Right. We basically just need to define a tag that is ignored by knossos, but still written unchanged on the next save. Call it <task> for example and leave it to the server to define and interpret attributes.

**Comment by Optiligence** [comment]
`/knossos/session` only supplies a `␣/␣` separated category-task-name string combination as attribute `task` of `<session>` or as `taskname` as part of the Content-Disposition header of `/knossos/newTask` (which is currently discarded). 
I suggest adding the tag `<task category="" name=""`/> to both nml and `/knossos/session`.

**Comment by fabiansvara** [comment]
We can add this easily, but will then have to add a root node for the two tags in /knossos/session, so the format will start looking somewhat redundant. I think it would be less unaesthetic to add two attributes to the session tag.

**Comment by Optiligence** [comment]
`session` _is_ the root node

**Comment by fabiansvara** [comment]
Currently, yes. Are you suggesting we do something like

    <session taskname="..." ... >
      <task name="..." ... />
    </session>
? That's what I meant by redundant

**Comment by Optiligence** [comment]
No need to specify `task` as `session` attribute if it’s a child element already.

**Comment by Optiligence** [comment]
only the new format is supported in KNOSSOS now
