### ISSUE TITLE
Viewport mislocalization upon maximize/restore

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#269]
When a viewport (left-bottom for example) is set to a big-enough geometry in maximized knossos window,
then upon restoration to a partial knossos window some of the viewport is hidden. This could have made sense, but when one attempts to move the viewport, then even before actually moving the mouse, the viewport moves/reallocates (doesn't matter) so that now it is all visible. This behavior looks ill, even if for some other reason it had made sense to be programmed as it is.

**Comment by my-tien** [comment]
I don't think this is a real issue. The only reason why one clicks on a viewport is to see and interact with its contents.

From this perspective it could be viewed as a convenience feature that KNOSSOS automatically moves a vp completely into view when it was only partially visible ^^

**Comment by orenshatz** [comment]
First of all the viewports are not necessarily touched when they are viewed, so you want to force the user touching it in order for it to show correctly.
But anyway, simply touching the viewport is not what triggers the repositioning, it's actually attempting to *move* the viewport which does so. Just try.
