### ISSUE TITLE
overlay paint brush bucket fill

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#273]
Instead of per-coordinate brush operations, a lasso enclosure is painted, automatically bucket-filled and the operation is applied for the entire fill at once.

**Comment by my-tien** [comment]
Conveniently we already have the bucket fill feature on middle-click. One could simply draw a circle with the brush and then middle-click the center.

**Comment by orenshatz** [comment]
In which brush mode do we have the middle-click?
I already have plugins that use the middle-click. Is this a new shortcut?

**Comment by my-tien** [comment]
In both modes, it's not new
