### ISSUE TITLE
Should display an error when loading a file fails

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#277]
... this is printed on the command line, but the Knossos title bar is updated to contain that file's path anyway, as if loading had worked and no message is displayed through the GUI.

Debug: opening "/home/svara/work/mpi/Electron Microscopy/EM analysis/Volume Tracing/for_heidelbrain_tasks/from_prediction_aug15/mem_block_99.k.zip" for reading failed

**Comment by orenshatz** [comment]
It's nice to know I'm not the only one who's still awake.
