### ISSUE TITLE
'a' key to add a single un-linked note

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#278]
...should at least work in "Advanced Tracing" mode.

**Comment by Optiligence** [comment]
we removed this feature as it was thought to be only a workaround for creating a new tree

**Comment by my-tien** [comment]
What are the use cases of the single unlinked node?

**Comment by fabiansvara** [comment]
Special annotation formats require unlinked nodes or parts of the tree

**Comment by fabiansvara** [comment]
To clarify, there are cases where grouping different annotation parts together in a tree with a common identifier and meta-data comment is useful, e.g. a tree representing a synaptic location with labels for presynapse, postsynapse and contact site. Eventually, we should implement nested annotation object groups that would make that kind of stuff obsolete, but currently, it's still important.

**Comment by Optiligence** [comment]
There still is the unlinked mode. 
The idea of swapping modes after one node was placed seemed a bit weird. 
But sure we can add it back if you think it’s more important than confusing.

**Comment by Optiligence** [comment]
How do we proceed on this. I don’t like automatically switching modes, so if we add it back, i would add it as a toggle in linked mode with an indicator in the statusbar.
