### ISSUE TITLE
acitve node ID rendering opt-in

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#279]
...and obscures the view of very small structures.

**Comment by Optiligence** [comment]
Then disable it

**Comment by fabiansvara** [comment]
The active node ID is always rendered

**Comment by Optiligence** [comment]
Then hide the skeleton with `1` — obstruction free. The text is hardly blocking more data than the node itself.

**Comment by fabiansvara** [comment]
... the skeleton offers useful information, the node id doesn't. You barely ever do things based on node ID in knossos these days, and if you really need it, it's in the tree view.

**Comment by orenshatz** [comment]
The node radius can be controlled, but the number cannot.
I suggest the number would not show as default, and only enabled by a checkbox.
