### ISSUE TITLE
"Fill with no-label" in paint mode

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#285]
When using the filling in paint mode, when the fill is not constrained by a boundary, a very large region will be filled. Without undo, it is quite painful to revert this. A simple solution would be to allow "filling with no label" (Shift-middle click, by analogy with erase).

**Comment by fabiansvara** [comment]
... I just realized this would not work under the current behavior of the filler, which does not stop when it encounters a label ID different from the one at which the user clicked, but apparently only stops when it encounters the currently active ID. This is quite unexpected, because it is very different from what other painting tools do.  Was there a reason for this decision?

**Comment by Optiligence** [comment]
i don’t think there was a reason, changed in 051c6be8209a198501c6445afaff16f20a0754c5
