### ISSUE TITLE
Explicit representation of synapses

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#287]
Up for discussion. Would help in improving compatibility with third-party backends.

**Comment by al3xst** [comment]
Visual representation of synapses was introduced with https://github.com/knossos-project/knossos/commit/8c520a625f1644c91946cec9a1df659d5ffbea88
Since then the functionality and usability has been improved, we should now test if everything works as expected.

**Comment by Optiligence** [comment]
yee
