### ISSUE TITLE
No more skeleton nodes / trees shown

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#30]
Loading an nml, clearing the skeleton and loading a different skeleton sometimes can lead to a state where no nodes and tree are shown (in tree view and open vis.). Closing Knossos and starting it again fixed the issue. Nmls were loaded via dragn drop in the old .nml format. Knossos showed the filename correctly in the titlebar.

**Comment by Optiligence** [comment]
Did this happen lately?

**Comment by jmrk84** [comment]
Not anymore
