### ISSUE TITLE
knossos fails to start after installing the .deb

### ISSUE THREAD

**Issue by raacampbell13** [knossos-project/knossos#301]
I installed the .deb from version 4.1.2 on Linux Mint 17.2. When I attempt to start it, the following happens:

```
$ /opt/knossos/knossos 
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[knossos.cpp:360]       Debug: Error reading config file at path:knossos.conf
[treeLUT_fallback.cpp:30]       Debug: entered load tree LUT fallback
[segmentation.cpp:135]  Debug: could not open »stdOverlay.lut«
[segmentation.cpp:135]  Debug: could not open »stdOverlay.lut«
Segmentation fault
```

If you could give me some quick compiling instructions I could try to build from source.

**Comment by Optiligence** [comment]
That’s a packaging issue and we didn’t get to solving that yet. 
You can try the deb package of the previous version. 
We are working on getting out a new release soonish. 

I updated the [build instructions](https://github.com/knossos-project/knossos/wiki/Build-Instructions#step-by-step-setting-up-a-linux-build-environment) page which is (from our perspective) to prefer over a *.deb package.

**Comment by raacampbell13** [comment]
I confirm that 4.1.1 works.
