### ISSUE TITLE
Streaming stopped working for resource-built e**** datasets

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#313]
JP2 files download fine, but nothing is shown.
In contrast, the j0126 streaming of JPG files works fine.
I would suspect either JP2 itself stopped working, or something
peculiar about the conf params (scale?) of those datasets is broken.

**Comment by Optiligence** [comment]
openJPEG incorrectly set the colorspace of the public dataset cubes (this is fixed in their master, but not in any public release), the Jasper library in use by KNOSSOS through Qt denies to decompress them because of that.  
They are scheduled to be recubed as jpg.

**Comment by orenshatz** [comment]
I don't get it, why is this only manifesting now, did we replace our JPEG2000 library recently?
As I recall, I've included a static copy inside our code base, was it replaced by the pacman approach?

**Comment by orenshatz** [comment]
(and how come there was no open bug for it till now...?
or was there another issue for replacing the jp2 to jpg somewhere?)
