### ISSUE TITLE
missing return value as error instead of warning

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#314]
I have no idea why the compiler doesn't force an error on it, as the return value is essentially defined by whichever garbage in the stack/registers.
I just encountered a bug manifested due to a lack of return statement at the end of my function, but it would have been much harder to find in case the function seldom returns at the end.

**Comment by Optiligence** [comment]
playing google here: http://stackoverflow.com/a/6261198
`-Werror=return-type`, one could also use global `-Werror`, but maybe some of the minor warnings get in the way during development.

**Comment by Optiligence** [comment]
Since we got rid of all the warnings, everybody should be able to notice when they get warnings for changes. 
I still take the view that `-Werror` is too intrusive during development and will therefore not enforce it.
