### ISSUE TITLE
Drag and drop of a few (83) annotation files leads to slowness and unresponsiveness

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#320]
... even when just one tree is shown. This does not happen for the release. Most recent master.

**Comment by jmrk84** [comment]
Hard to reproduce. Might have something to do with switching datasets before.

**Comment by Optiligence** [comment]
any new hints?

**Comment by Optiligence** [comment]
maybe something similar to #365, we’ll never know
