### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by jakirkham** [knossos-project/knossos#332]
What is this Licensed under? Could a License file be added to the repo and possibly a note in the Readme to clarify this please?

**Comment by Optiligence** [comment]
GPL2
A license text can be found in some of the source files, e.g. https://github.com/knossos-project/knossos/blob/master/viewer.h
We weren’t really thorough in adding this to every file and will see about making it more clear.

**Comment by al3xst** [comment]
License information clarified with the following commits
https://github.com/knossos-project/knossos/commit/5c7633959a922f0c018b44923656863309e268a2
https://github.com/knossos-project/knossos/commit/bc22285c926b3722862db6b4844c368b1cb12400
