### ISSUE TITLE
O(n^2?) complexity for adding nodes from Python plugin interface

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#336]
KnossosModule.skeleton.add_node(id, x,y,z, tree_id)
has terrible performance, basically rendering the function useless (apart from adding single nodes). Attached is a file that contains times [s] for ~20k calls to add_node with a real world skeleton, illustrating how performance degrades. I suspect that tables / skeleton rendering get updated for every call to add node or something similar. Not showing the node list widget brings no improvement however.
[dbg_times.txt](https://github.com/knossos-project/knossos/files/245191/dbg_times.txt)

**Comment by jmrk84** [comment]
const auto blockState = this->signalsBlocked();
    blockSignals(true);

appears to be the solution for loading skeletons from xml

**Comment by jmrk84** [comment]
Calling
KnossosModule.knossos_global_skeletonizer.blockSignals(True)
... add you nodes ...
KnossosModule.knossos_global_skeletonizer.blockSignals(False)

solves the issue.
Not sure whether there are any unwanted side effects.

**Comment by Optiligence** [comment]
There are, please use: 
```
signalsBlocked = KnossosModule.knossos_global_skeletonizer.blockSignals(True);
... add you nodes ...
KnossosModule.knossos_global_skeletonizer.blockSignals(signalsBlocked);
KnossosModule.knossos_global_skeletonizer.resetData();
```
instead.
