### ISSUE TITLE
Node ID input is broken

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#338]
Since you currently can't type in an invalid node ID in Annotation View / Commands, jumping to a specified node ID is broken, as the intermediate inputs also have to be valid.

**Comment by Optiligence** [comment]
Right, validation was linked to the wrong signal. 
But anyway, the Commands tab is gone since yesterday.

**Comment by my-tien** [comment]
I removed the commands tab and migrated the default node radius and locking to a collapsible widget below the nodes table. 
I believed that navigation in the viewport as well as through the tables was sufficient and that no one would want to explicitly type in node IDs anymore.

**Comment by fabiansvara** [comment]
Users sometimes refer to node IDs and it can be useful for debugging, so node ID input is required.

**Comment by Optiligence** [comment]
`KnossosModule.skeleton.find_node_by_id(node_id)`^^

**Comment by Optiligence** [comment]
option in skeleton view ctx menu
