### ISSUE TITLE
Allow loading jpeg cubes from harddrive

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#342]
...let me know if there is some trick to do this already now. If not, we should implement it. This would probably be a good opportunity to clean up the knossos.conf format, too.

**Comment by Optiligence** [comment]
Should work with no tricks necessary.

**Comment by fabiansvara** [comment]
Ok, great. The next step is to do compressed cubes from HD, and uncompressed over HTTP. Very useful for datasets that can't fit on a single external HD.

**Comment by Optiligence** [comment]
You mean local jpeg cubes but pressing 5 loads from online? This is basically the multiple layers issue because it requires several loaders/dataset configurations.

**Comment by fabiansvara** [comment]
Yes, that's what I meant. The dataset never has to be loaded from different sources at the same time, though, so it should be simpler than full multilayer support..

**Comment by Optiligence** [comment]
enumeration/selection of different dataset sources with only one at a time is the first step, yes

**Comment by Optiligence** [comment]
I’m gonna close this, multiple layers are at #84
