### ISSUE TITLE
Crash (segault) on delete tree

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#346]
Can't currently reproduce. This was triggered by selecting multiple trees in annotation view and pressing the DEL key. Build is 4.1.2-651-g22d2742, so a bit old already.

**Comment by Optiligence** [comment]
i don’t think it’s worth to investigate
it’s probably fixed

**Comment by fabiansvara** [comment]
... actually it seems this is due to memory corruption upon removing node comments. I got the segfault on save now, after removing 10 comments (Search for node comment, go through the list of matches, double click on comment, backspace to remove comment, for all matches). This is the same thing I had done just before the last crash.

**Comment by Optiligence** [comment]
and node comments don’t exist the way they did before anymore…
