### ISSUE TITLE
No light effects for active tree when highlighted

### ISSUE THREAD

**Issue by my-tien** [knossos-project/knossos#351]
It’s hard to recognize overlapping structures without light effects:
![photo321236470133270470](https://cloud.githubusercontent.com/assets/3898364/17068768/3186fcf6-5053-11e6-9b8f-a0742ecbe184.jpg)
![photo321236470133270471](https://cloud.githubusercontent.com/assets/3898364/17068770/338d8150-5053-11e6-85d9-84833420b13e.jpg)

**Comment by Optiligence** [comment]
as you can see, also not for individually highlighted nodes (comments)
