### ISSUE TITLE
Jump to node broken when clicking on filtered nodes

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#355]
1) Comment filtering
2) Try to jump to one of the result-nodes
=> Always jumps to the same, different node, i.e. not one of the nodes it should jump to. Context menu has "jump to node" gray.

**Comment by jmrk84** [comment]
I think it always jumps to the currently active node

**Comment by Optiligence** [comment]
If the action is disabled (grey) it shouldn’t be possible to trigger it with double click. 
Its disabled when more than one node is selected. 
Why is your selected node not active?

**Comment by jmrk84** [comment]
Selecting a row doesn't make a node active in the filtered view

**Comment by Optiligence** [comment]
Then this is the same as tge tree issue. 
Tge active node is still selected (green in the vps) and new selections don’t change that.

**Comment by jmrk84** [comment]
This is a serious blocker, it makes it impossible to work normally with Knossos.
