### ISSUE TITLE
Default orientation in skeleton VP changed

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#356]
The  new default orientation of the dataset makes no sense. It should start with the xy-slice at the top, as it used to be.

**Comment by Optiligence** [comment]
The origin is in the top left and you look z→0, so…

**Comment by jmrk84** [comment]
This is how it should look roughly on default

![3d_7218_7728_332_j0256_mag1](https://cloud.githubusercontent.com/assets/7120954/18511692/772d6fea-7a85-11e6-8390-4364daab6937.png)

**Comment by Optiligence** [comment]
No, because that makes no sense^^
Try to rotate it in such a way that you have xy, origin top left and look towards z=0 (hint: you can’t). 
That’s the way KNOSSOS handles the dataset.

**Comment by Optiligence** [comment]
wut, i did expect x and y to be switched in your image (as it was before in K)

**Comment by jmrk84** [comment]
So what happened? I didn't look at x and why, this is minor compared to the z direction for me at least

**Comment by Optiligence** [comment]
the way you rotated the dataset here is, that the origin is closer to the camera as the other end of the dataset

**Comment by Optiligence** [comment]
Currently all ortho vps origin in the top left and the skelvp rotates according to the following: 
xy z→0
xz y→∞ (xy camera rotated -90° around the x axis)
zy x→∞ (xy camera rotated 90° around the y axis)

Which is – I guess – the exact opposite of what is wanted, which would be z→∞ as well as y→0 (90°) and x→0 (-90°). 
To achieve this, the skelvp content has to be mirrored on the xy plane and the rotation has to be adapted accordingly.
