### ISSUE TITLE
Active tree should be red

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#357]
When zoomed out, the active tree currently looks brown

**Comment by al3xst** [comment]
Seems to be an issue (shadow) with the light effects. 
In Preferences -> Trees, if you turn off "Enable light effects" the trees are bright again. 
Maybe we can disable this feature for active tree or highlight the active tree somehow differently?

**Comment by my-tien** [comment]
Well, #351 was the result of that.

**Comment by fabiansvara** [comment]
Making the light effects dependent on the zoom level by default should solve it. I see your point in #351, but when zoomed out it has no advantage and makes the contrast really bad.
