### ISSUE TITLE
Wiggle stereo option for 3D viewport

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#361]
A nice enhancement to the 3D viewport would be a button temporarily activating a wiggle stereoscopy mode (https://en.wikipedia.org/wiki/Wiggle_stereoscopy). I use this a lot by manually moving the camera back and forth and it's actually useful. A dedicated button would make it easier to discover this for new users. The most effective way to trigger the 3D apparance for me is to basically move the camera along a circle around the axis pointing into the monitor.

**Comment by fabiansvara** [comment]
... a key to hold down would probably be the best way to do this

**Comment by al3xst** [comment]
I added some basic wiggle functionality. The 3d Viewport must be focused and you need to hold the key 'w' (for wiggle). 
Should you also be able to increase/decrease the distance between the 2 pictures?

**Comment by fabiansvara** [comment]
This is nice already, but it should wiggle both horizontally and vertically for a better stereo effect.
