### ISSUE TITLE
Severe tracing (regular skeletonization) speed regression

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#365]
With a medium-size skeletons, Knossos adds a pause of roughly 1s after placing a node.

**Comment by jmrk84** [comment]
... possibly picking / culling related?

**Comment by jmrk84** [comment]
The skeleton file I'm using has ~500k nodes, but the problem happens when only one tree is shown of them, i.e. much less than the 500k.

**Comment by Optiligence** [comment]
There is no regression. 
The only time node placement is delayed heavily, is, when all nodes of the skeleton are shown in the table _and_ the table is sorted – therefore having to sort _all_ nodes upon new node creation. 
This delay is reasonable.
