### ISSUE TITLE
Keyboard shortcut re-org is a problem

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#369]
I can see that the shortcut re-organization helped with consistency, but you have to keep in mind the experience of users who might have memorized the keys for a possibly very long time. The "1" key has become a real trap, since you used to press it all the time to get a better view of the data in previous Knossos versions. Now, it overwrites the active node comment. This can lead to loss and / or corruption of important data.

**Comment by Optiligence** [comment]
I understand your concern. 
One suggestion would be to make the comment shortcuts `ctrl`+number – any combo effectively prevents accidental use (think of ›create tree‹), but is less convenient to use.

**Comment by fabiansvara** [comment]
I'm Ok with that solution
