### ISSUE TITLE
Knossos hangs when streaming is enabled and no connection available on start up

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#37]
Reproduce with:
Select a streaming dataset. Stream. Close Knossos. Disable wifi. Start Knossos again.
=> Knossos hangs until something times out. This is unexpected behavior - just showing black cubes is much more acceptable for users, even better would be a message box indicating that the streaming dataset could not be opened due to connection problems

**Comment by Optiligence** [comment]
there should be an abortable progress bar in loader wip
