### ISSUE TITLE
Restrict scale bars to human readable values

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#372]
Here a list that should be hardcoded:
10 nm
20 nm
50 nm
100 nm
200 nm
500 nm
1 µm
2 µm
5 µm
10 µm
20 µm
50 µm
100 µm
200 µm
500 µm
1 mm
2 mm
5 mm
10 mm
20 mm
100 mm
1 cm
2 cm
5 cm

**Comment by jmrk84** [comment]
This applies only to the 3d viewport, not the ortho viewport. They already use sane values.

**Comment by n0void** [comment]
The values follow a pattern but 50mm is missing. Is that intentional?

**Comment by Optiligence** [comment]
20 mm are also equal to 2 cm

**Comment by jmrk84** [comment]
10 mm is also the same as 1 cm ;). The point was to give you the idea. It would actually make more sense to implement this algorithmically, without an arbitrary limitation.

**Comment by Optiligence** [comment]
I don’t get any friends for suggesting decimal exponential notation, do I? (Apart from restricting it to 1, 2 and 5)
I was also wondering why unit prefixes are powers of 1000. 
The prefixes would have to be hard coded if there isn’t something like this available in Qt already.
