### ISSUE TITLE
Set radius on many nodes very slow

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#377]
Select 10k nodes, right click "set radius". Wait (forever?). Probably some signal pollution issue.

**Comment by Optiligence** [comment]
The question arises: At what count are individual signals not desirable anymore. (for any batch operation)

**Comment by jmrk84** [comment]
At the count that makes knossos unresponsive for more than 1 second or so. I would guess that everything > 100 is a good approximation. Is there actually any good reason to not always block signals for operations on more than one element?

**Comment by Optiligence** [comment]
The fine grained signals exist to reduce the complexity of editing a small number of elements. 
Even marking 10k elems as modified shouldn’t be as intensive as copying the entirety of the node set. 
If sorting is enabled or not probably has the largest impact.
