### ISSUE TITLE
"object with id 0 already exists"

### ISSUE THREAD

**Issue by pschubert** [knossos-project/knossos#382]
When loading more than one merge list in Knosos (or adding one if one is already loaded) Knossos fails to import with "object with id 0 already exists" and crashes.

Example merge lists:
[mergelist50972146.k.zip](https://github.com/knossos-project/knossos/files/782919/mergelist50972146.k.zip)
[mergelist29923063.k.zip](https://github.com/knossos-project/knossos/files/782920/mergelist29923063.k.zip)

**Comment by Optiligence** [comment]
It doesn’t crash. 
And yes, merging does’t imply id remapping for the segmentation.

**Comment by my-tien** [comment]
Your crash seems not to be related to the duplicate IDs.

**Comment by Optiligence** [comment]
Alright, it does crash when those 2 files are loaded and the segmentation tab of the annotation widget is selected.

**Comment by my-tien** [comment]
The crash was caused by the “object with id 0 already exists” exception due to which mergelist loading was left before signaling state was resetted properly.
