### ISSUE TITLE
Incorrect "Set Comment" action on annotation view node selection

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#396]
This is probably a symptom of some general issue with the annotation view and might take less to trigger, but if I have a node selection in Knossos (Shift-Drag to select nodes in the 3D viewport) and then, in the annotation view ...
- Filter Nodes on Comment
- Additionally filter Nodes on Selection
- Select all matching nodes in the annotation view list (Ctrl+A)
- Right click and choose "Set Comment"

... then the comment will be changed on all nodes that were selected in the 3D Viewport, not just those that are selected in the annotation view.

**Comment by Optiligence** [comment]
It’s not possible for the table to comprehend selected nodes which are filtered out. (If it would enforce this, it would mean that filtered out nodes wouldn’t be selectable at all)
I’m aware of this issue for quite some time but during the limited time i thought about it couldn’t think of a solution. 

You can workaround your issue if you clear the comment filter, select and enter the filter string again.

**Comment by Optiligence** [comment]
The filter options are applied pre-table and would have to explicitly handle (de)selections. (I’m not sure if this would fix every case)
The comment filter currently does exactly that through the table.
