### ISSUE TITLE
KNOSSOS does not show anymore whether a jpg or raw channel is displayed

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#399]
This used to be under the zoom settings.

**Comment by Optiligence** [comment]
It’s in the action menu.

**Comment by jmrk84** [comment]
I see, sorry. It would maybe still make sense to leave it next to the magnification, it fits much better there. But this could maybe be changed for the channels anyway.

**Comment by Optiligence** [comment]
the zoom widget is on death row for some time now
