### ISSUE TITLE
Optionally load settings from .k.zip file

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#406]
It must be possible to leave certain settings out, ideally simply by not specifying them in the settings / ini file contained in the .k.zip.

**Comment by Optiligence** [comment]
https://bugreports.qt.io/browse/QTBUG-40121
`loadCustomPreferences` already applies on top of the current settings

**Comment by Optiligence** [comment]
https://bugreports.qt.io/browse/QTBUG-696

**Comment by Optiligence** [comment]
the custom settings have to be remembered explicitly (#329)
