### ISSUE TITLE
Viewport size not restored correctly beyond a certain size

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#408]
When maximizing the Knossos main window and increasing a viewport to its maximal size, on the next Knossos run it will be larger than usual, but not the maximal size.

**Comment by Optiligence** [comment]
maximizing isn’t applied until an event is run, vp setup therefore uses the unmaximized size as basis for size calculations

**Comment by Optiligence** [comment]
show seems to suffice it seems
