### ISSUE TITLE
Log Python Console to a file

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#411]
Would be great if Knossos could log python console output to a file, for debugging (by different person for example) at a later time point.

**Comment by Optiligence** [comment]
It doesn’t show up in the log file?

**Comment by fabiansvara** [comment]
I didn't know it was supposed to, but I don't see anything there. Wer're talking about "log.txt"?

**Comment by Optiligence** [comment]
We are. I wasn’t sure if it was, but it should go there.
