### ISSUE TITLE
Knossos Preventing Node Placement in Visible Region

### ISSUE THREAD

**Issue by nguzman313** [knossos-project/knossos#413]
While tracing a confocal microscopy image in Knossos 5.0.1, my colleague has run into trouble placing nodes at particular coordinates, specifically the Y-coordinate. For all Y-coordinates less than 1000, there is no issue placing a new node. However, Knossos is not allowing node placement for all Y-coordinates greater than 1000 for this particular data set. The Y-boundary of the data set is 1788, so there should be no issues placing nodes for Y-coordinates less than 1788. Any help in this matter is greatly appreciated.

**Comment by my-tien** [comment]
That sounds strange.
Can you move beyond 1000 in y-direction?
Can you verify that the node counter at the bottom of the annotation widget (Windows ↦ Annotation) does not increment?

**Comment by Optiligence** [comment]
Where you able to resolve the issue?
