### ISSUE TITLE
brush not visible in the new nightly build (likely outdated intel gfx drv)

### ISSUE THREAD

**Issue by adwanner** [knossos-project/knossos#414]
In contrast to the current release (v5.0.1), the brush is not visible any more  in "Segmentation Paint" mode in the most recent win64.standalone.KNOSSOS.nightly.exe. 
OS: Windows 7 Home Premium on an Acer Aspire 7750Z

**Comment by Optiligence** [comment]
Cannot reproduce. 
Can you provide the revision string from the about dialog and provide a screenshot of the missing cursor?

**Comment by adwanner** [comment]
Revision: v5.0.1-78-g30a5c95c-dirty
Revision Date: 2017-06-02T14:46:42+02:00

![no_brush](https://user-images.githubusercontent.com/17795672/26986788-53eedf36-4d49-11e7-8e6a-84e8f2f6d7d0.png)

**Comment by adwanner** [comment]
Unfortunately, the does not get captured by print screen.

**Comment by adwanner** [comment]
Here a mobile screenshot
![20170609_193638](https://user-images.githubusercontent.com/17795672/26987382-ac81e114-4d4b-11e7-9f5e-16e294d9c1e6.jpg)

**Comment by Optiligence** [comment]
Thx, I currently have no idea though.

**Comment by adwanner** [comment]
Strangely enough, the brush is perfectly visible with Revision v5.0.1, from 2017-03-18T02:52:06+01:00

**Comment by Optiligence** [comment]
is there any output?

**Comment by adwanner** [comment]
That's all I get if I run it with cmd: 
```
Warning: Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Debug: 3.1.0 - Build 8.15.10.2418 Intel Intel(R) HD Graphics Family
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: "No errors.\n"
Debug: Lowest Mag: 1, Highest Mag: 16
Debug: Allocating 54 MiB for the datacubes.
Debug: Allocating 432 MiB for the overlay cubes.
Debug: viewer returned
```

**Comment by Optiligence** [comment]
You can try different earlier builds, espsecially [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.89/artifacts) and [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.90/artifacts).

**Comment by my-tien** [comment]
Does the brush appear if you increase the depth cutoff (Preferences ↦ Trees), possibly to something large?

**Comment by my-tien** [comment]
And does it paint despite being invisible?

**Comment by adwanner** [comment]
Increasing the depth cutoff up to 99.99 did not help, the brush is still invisible although painting works.

**Comment by Optiligence** [comment]
Did you try any other nightlies?

**Comment by adwanner** [comment]
I tried the other nightlies, in both the brush is visible.

**Comment by Optiligence** [comment]
We can bin search then, what about [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.136/artifacts)?

**Comment by adwanner** [comment]
not visible in nightly116.

**Comment by Optiligence** [comment]
116, not 136?

**Comment by adwanner** [comment]
right, this was 136 - sorry.

**Comment by Optiligence** [comment]
how about [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.128/artifacts)?

**Comment by adwanner** [comment]
In 128 the brush is visible

**Comment by Optiligence** [comment]
[this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.131/artifacts)?

**Comment by Optiligence** [comment]
w8, this one probably has the wrong binary

**Comment by Optiligence** [comment]
[this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.132/artifacts) one instead

**Comment by Optiligence** [comment]
Alternatively: does the brush appear if you disable mesh rendering in ortho vps (Preferences → Trees)?

**Comment by adwanner** [comment]
Indeed, disabling mesh rendering in the orthogonal viewports solves the issue in v5.0.1-80-g1263ee3f

**Comment by Optiligence** [comment]
That’s good _and_ bad. 

Does the snapshot (preview) work correctly for you?

**Comment by adwanner** [comment]
Yes, the screen shots made by "Snapshot Preview" look ok

**Comment by Optiligence** [comment]
Can you test [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.180/artifacts) with enabled mesh rendering?

**Comment by adwanner** [comment]
It's still the same in 180 as before: The brush is only visible if mesh rendering is disabled.

**Comment by Optiligence** [comment]
I’m trying a little bit, what about [this](https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.181/artifacts) and can you give the console output with mesh rendering disabled as well as enabled?

**Comment by adwanner** [comment]
Still the same behavior as before. Attached I send you the console output.
[MeshEnabled.txt](https://github.com/knossos-project/knossos/files/1072957/MeshEnabled.txt)

[MeshDisabled.txt](https://github.com/knossos-project/knossos/files/1072958/MeshDisabled.txt)

**Comment by Optiligence** [comment]
I’m out of ideas for now.

**Comment by adwanner** [comment]
Thanks a lot for digging into it anyway - I really appreciate. For now it's fine to disable mesh rendering when I need to see the brush.

**Comment by Optiligence** [comment]
I just tested on a sandy-bridge notebook with the [latest available driver](https://www.intel.com/content/www/us/en/support/graphics-drivers/graphics-for-2nd-generation-intel-processors.html) and the brush works.

**Comment by Optiligence** [comment]
Did you try updating your driver?
