### ISSUE TITLE
Application closes immediately after opening

### ISSUE THREAD

**Issue by jcohenadad** [knossos-project/knossos#459]
Hi,
I downloaded this version: macos.KNOSSOS-5.1
I am running OSX 10.13.3.
When opening the application, the KNOSSOS logo appears, and then the application closes immediately.

**Comment by Eroica** [comment]
Hi,

could you try running KNOSSOS from the command-line? You can do it like this:

Navigate to the directory where KNOSSOS.app is located (e.g. `/Applications`): `cd /Applications`

Then run KNOSSOS' executable: `./knossos.app/Contents/MacOS/knossos`

Just copy and paste the output of the Terminal for us. This allows us to see where exactly KNOSSOS fails to launch.

**Comment by jcohenadad** [comment]
~~~
./knossos.app/Contents/MacOS/knossos 
Warning: Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
~~~

**Comment by Eroica** [comment]
Thanks for the report, this is a bug in our build system. We are linking KNOSSOS with the wrong Python library.

For now, you should be able to run KNOSSOS from the command-line by prepending a suitable PYTHONHOME environment variable. If you are in `/Applications`

    PYTHONHOME=/usr knossos.app/Contents/MacOS/knossos

Or for some specific shells:

    env PYTHONHOME=/usr knossos.app/Contents/MacOS/knossos

**Comment by Eroica** [comment]
I updated the .app package to include the correct Python library. You should be able to run KNOSSOS normally after downloading the new package from our releases (https://github.com/knossos-project/knossos/releases/download/v5.1/macos.KNOSSOS-5.1.zip).
