### ISSUE TITLE
knossos does not jump to double-clicked node when too close too its position

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#475]
How to reproduce:
Under annotation, double click a node row with;
Expected behavior: knossos jumps to the exact coordinate of the node
Outcome: knossos jumps only to the exact coordinate of the node if the current position is suficiently far away.

**Comment by Optiligence** [comment]
can’t repro

i can move 1 voxel and and double click the node id and it jumps the voxel back

it only works in the id column, did you use that?
