### ISSUE TITLE
Can't execute on ubuntu 20.04

### ISSUE THREAD

**Issue by iratxeMoya** [knossos-project/knossos#497]
I have executed chmod +x but when double clicking the executable does nothing. I do not know what can be the error.

**Comment by Optiligence** [comment]
cat you try `sudo apt install python2.7`?

**Comment by iratxeMoya** [comment]
I just did it, and nothing changed. Same issue.

**Comment by Optiligence** [comment]
hm, can you start it from the terminal and check for output there?

for reference: it’s working on 20.04 here, so there should be a way to get it working

**Comment by iratxeMoya** [comment]
how can I do that?

**Comment by Optiligence** [comment]
`~/Downloads/linux.KNOSSOS-5.1.AppImage` i assume

**Comment by Optiligence** [comment]
ok, the 5.1 release works here, the nightly doesn’t
did you test the nightly?

**Comment by iratxeMoya** [comment]
I tried this:
![image](https://user-images.githubusercontent.com/53813246/99826107-33234d00-2b58-11eb-85d5-3b5112a25fdc.png)

**Comment by Optiligence** [comment]
if you are in the folder you need to append `./` to start a program from that folder

i.e. `./linux.KNOSSOS-5.1.AppImage`

**Comment by iratxeMoya** [comment]
I thing is the release, not nightly

**Comment by iratxeMoya** [comment]
oh, now an error is displayed. I think is about python... I will try to solve it 
![image](https://user-images.githubusercontent.com/53813246/99826318-7ed5f680-2b58-11eb-93a9-c826cce2cbc6.png)

**Comment by iratxeMoya** [comment]
solved, thanks!

**Comment by Optiligence** [comment]
what did you do to solve it?

we will also work on that that wont be necessary for future releases…

**Comment by iratxeMoya** [comment]
yeah, sorry,

I've first located the libpython2.7.so.1.0 file 
locate libpython2.7.so.1.0
and then added this path to  /etc/ld.so.conf file. Finally I executed ldconfig and worked
