### ISSUE TITLE
windows network URLs break the datasetloadwidget on Linux

### ISSUE THREAD

**Issue by my-tien** [knossos-project/knossos#498]
Had a .k.zip with a URL like this

    file://192.168.6.1/path/to/some_dataset.conf

After dropping it into K under Linux, the dataset did not load. When opening the DatasetLoadWidget, it is disabled. The progress bar at the lower left corner stayed empty.
After closing K, the error is revealed:

    Debug: QVariant(Invalid) QNetworkReply::ProtocolInvalidOperationError "Request for opening non-local file file://192.168.6.1/path/to/some_dataset.conf"
    Debug: no config at QUrl("file://192.168.6.1/path/to/some_dataset.conf")

**Comment by Optiligence** [comment]
The replies for those URLs are finished very fast (or instantly) and don’t seem to emit their `finished` signal.
