### ISSUE TITLE
.swc file of skeletons is empty

### ISSUE THREAD

**Issue by smcelroy97** [knossos-project/knossos#507]
I am trying to export .swc files from a segmented EM dataset of neuron skeletons. For both options (save as um and save as px) the swc file contains zero bytes and is empty.

**Comment by my-tien** [comment]
Hi, the swc export does not work on segmentation, it exports KNOSSOS skeletons into swc format. Since conversion from segmentation to skeleton can have multiple possible solutions depending on the input we have so far not implemented this feature.

**Comment by smcelroy97** [comment]
Hello,

When I right click on my merged trees on the skeleton tab of the annotation window I have the option to save as SWC. That skeleton contains zero bytes when saved, do I need to do something else to save this skeleton?

Scott

From: My-Tien Nguyen ***@***.***>
Date: Saturday, June 24, 2023 at 11:24 AM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

Hi, the swc export does not work on segmentation, it exports KNOSSOS skeletons into swc format. Since conversion from segmentation to skeleton can have multiple possible solutions depending on the input we have so far not implemented this feature.

**Comment by my-tien** [comment]
No, as long as you have a skeleton with nodes inside, that should be enough. Do you mind sharing the skeleton here? Or any dummy skeleton that doesn't work for you.

**Comment by smcelroy97** [comment]
Should I save as a kzip?

Scott

**Comment by my-tien** [comment]
Yes, exactly

**Comment by smcelroy97** [comment]
Here's a random cell I grabbed.

**Comment by my-tien** [comment]
You seem to have forgotten the attachment

**Comment by smcelroy97** [comment]
Weird it shows that I did attach it.

**Comment by smcelroy97** [comment]
Were you able to see the attachment? It was attached in the last two emails and this one.

From: Scott McElroy ***@***.***>
Date: Tuesday, June 27, 2023 at 3:30 PM
To: knossos-project/knossos ***@***.***>
Cc: knossos-project/knossos ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)
Weird it shows that I did attach it.

On Tue, Jun 27, 2023 at 2:30 PM My-Tien Nguyen ***@***.******@***.***>> wrote:

You seem to have forgotten the attachment

**Comment by my-tien** [comment]
Unfortunately no. Alternatively, you could also choose export to nml instead of saving to kzip. Then you can open the saved file in any text editor and copy-paste us the content per email.

**Comment by smcelroy97** [comment]
The file has very many lines, so I only copied a snippet of the text. The nml file is also attached.

Scott Mcelroy
<?xml version="1.0" encoding="UTF-8"?>
<things>
    <parameters>
        <experiment name="fw363"/>
        <lastsavedin version="v5.1-921-g794e0672"/>
        <createdin version="v5.1-709-g71343ab7"/>
        <guiMode mode="none"/>
        <dataset path=https://agglomeration.ariadne.ai/dataset/2021-12-24.pyk.conf overlay="1"/>
        <MovementArea min.x="0" min.y="0" min.z="0" size.x="42587" size.y="33791" size.z="23390" max.x="42587" max.y="33791" max.z="23390"/>
        <scale x="14" y="14" z="25"/>
        <RadiusLocking enableCommentLocking="0" lockingRadius="100" lockToNodesWithComment="seed"/>
        <time ms="1560000" checksum="23b63ba114b486385aa6321f03fc0d34a87a3d447e2046e2adf315aa12364cc3"/>
        <segmentation backgroundId="0" lockNewObjects="0" defaultMergeClass=""/>
        <editPosition x="14337" y="17079" z="19905"/>
        <skeletonVPState E0="0.135608" E1="0.801174" E2="-0.582867" E3="0" E4="-0.967503" E5="0.233804" E6="0.0962748" E7="0" E8="0.213412" E9="0.550872" E10="0.806846" E11="0" E12="298639" E13="-251744" E14="190095" E15="1" translateX="315194" translateY="345740"/>
    </parameters>
    <thing id="255" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1.">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5751393649" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1.">
        <nodes/>
        <edges/>
   </thing>
    <thing id="5955372119" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1.">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5542966146" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5542966147" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5542966212" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5542966307" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5542968832" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5543040864" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5543059467" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5543059485" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5543059521" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5543060068" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076284" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076293" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076340" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076376" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076388" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076389" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076390" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076419" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
   </thing>
    <thing id="5545076437" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076438" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076561" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076622" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545076813" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545077053" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095306" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095338" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095413" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095499" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095536" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095596" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095701" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095798" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095825" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095826" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095827" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095877" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545095978" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545096035" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545096036" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545096356" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545096573" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545096595" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545114422" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115062" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115653" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115657" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115658" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115659" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115678" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115688" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>
    </thing>
    <thing id="5545115701" visible="1" color.r="-1." color.g="-1." color.b="-1." color.a="1." nuc="10061538" anchor="5542968832">
        <nodes/>
        <edges/>


From: My-Tien Nguyen ***@***.***>
Date: Wednesday, June 28, 2023 at 5:48 PM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

Unfortunately no. Alternatively, you could also choose export to nml instead of saving to kzip. Then you can open the saved file in any text editor and copy-paste us the content per email.

**Comment by my-tien** [comment]
Okay, so the issue is that none of your trees contain any nodes. So there isn't really anything to export.
Could you explain what you are trying to achieve?

**Comment by smcelroy97** [comment]
Essentially, I'd just like to export the morphologies of all cells within a
certain nucleus as swc files, but am currently just trying to get it to
work for one cell. I was given a tutorial by the group who collected the
data and segmentation, and followed the steps listed on this google doc:
https://docs.google.com/document/d/e/2PACX-1vQg9CaH5TTZKeT6wLHxG-HzZBAebpa40LNyLOWRw50JsC681xIDiWQyNT3M-er22grwJGAfp5mKpPr4/pub
I have never worked with EM data so I'm not sure what I am doing wrong.

Best,
Scott

**Comment by my-tien** [comment]
There are 3 formats that can be exported from KNOSSOS. Below you can see how they look like and how to export them. Since in your case no skeleton data has been created, you will get the best impression of the morphology by going for the mesh:

## 1. Skeleton data
a graph with vertices and optionally edges, can be exported as .swc
![image](https://github.com/knossos-project/knossos/assets/3898364/83ff47ac-ec20-45f0-ad5b-86d15ea09544)

## 2. Segmentation
a pixel/voxel-labeling that is visualized as colored areas/volumes. Can be converted to numpy matrices with https://github.com/knossos-project/knossos_utils
![image](https://github.com/knossos-project/knossos/assets/3898364/c6e8b8e9-6d9b-401f-b047-a2bad3bf9dc6)

## 3. Mesh
a 3D surface. After saving as .k.zip, there will be a .ply file within the .k.zip that you can extract and open in any 3D viewer such as Blender or Meshlab.
![image](https://github.com/knossos-project/knossos/assets/3898364/3f8c3627-63b9-41e9-9d17-35992bbd6cb6)

**Comment by smcelroy97** [comment]
I plan to use these morphologies for network modeling, but the modeling package only accepts .swc and .hoc. Basically, what you’re saying is that for me to export cells directly to swc I would need to manually label the skeletons of these cells rather than use the already segmented data? If that is the case I will need to figure out how to convert the mesh/numpy array into one of the filetypes that works for me.

From: My-Tien Nguyen ***@***.***>
Date: Thursday, June 29, 2023 at 3:11 PM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

There are 3 formats that can be exported from KNOSSOS. Below you can see how they look like and how to export them. Since in your case no skeleton data has been created, you will get the best impression of the morphology by going for the mesh:

1. Skeleton data

a graph with vertices and optionally edges, can be exported as .swc
[Image removed by sender. image]<https://user-images.githubusercontent.com/3898364/249868630-83ff47ac-ec20-45f0-ad5b-86d15ea09544.png>

2. Segmentation

a pixel/voxel-labeling that is visualized as colored areas/volumes. Can be converted to numpy matrices with https://github.com/knossos-project/knossos_utils
[Image removed by sender. image]<https://user-images.githubusercontent.com/3898364/249869326-c6e8b8e9-6d9b-401f-b047-a2bad3bf9dc6.png>

3. Mesh

a 3D surface. After saving as .k.zip, there will be a .ply file within the .k.zip that you can extract and open in any 3D viewer such as Blender or Meshlab.
[Image removed by sender. image]<https://user-images.githubusercontent.com/3898364/249869868-3f8c3627-63b9-41e9-9d17-35992bbd6cb6.png>

**Comment by my-tien** [comment]
Yes, almost. This is what I hinted at in my first message: There is no trivial solution for a conversion from segmentation to skeleton because every small bump in the segmentation could in theory be turned into a branch of the skeleton. There are algorithms like skeletonize_3d from scikit-image or maybe you can have a look at https://github.com/seung-lab/kimimaro (haven't worked with it myself yet).

**Comment by smcelroy97** [comment]
Great, I’ll begin looking at these. Thank you for the help and patience, I really appreciate it!

Scott

From: My-Tien Nguyen ***@***.***>
Date: Thursday, June 29, 2023 at 5:18 PM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

Yes, almost. This is what I hinted at in my first message: There is no trivial solution for a conversion from segmentation to skeleton because every small bump in the segmentation could in theory be turned into a branch of the skeleton. There are algorithms like skeletonize_3d from scikit-image or maybe you can have a look at https://github.com/seung-lab/kimimaro (haven't worked with it myself yet).

**Comment by smcelroy97** [comment]
Hello,

I’m getting an error message when trying to load my k.zip files that reads “xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 17, column 128”
Do you know if this is an issue with what you mentioned about the data containing no nodes? Or is this a different issue?

Scott

From: Scott McElroy ***@***.***>
Date: Thursday, June 29, 2023 at 5:36 PM
To: knossos-project/knossos ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)
Great, I’ll begin looking at these. Thank you for the help and patience, I really appreciate it!

Scott

From: My-Tien Nguyen ***@***.***>
Date: Thursday, June 29, 2023 at 5:18 PM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

Yes, almost. This is what I hinted at in my first message: There is no trivial solution for a conversion from segmentation to skeleton because every small bump in the segmentation could in theory be turned into a branch of the skeleton. There are algorithms like skeletonize_3d from scikit-image or maybe you can have a look at https://github.com/seung-lab/kimimaro (haven't worked with it myself yet).

**Comment by smcelroy97** [comment]
Sorry, I didn’t mention I am trying to use load_kzip_seg from knossos_utils. If this is not your area of expertise, no problem.

From: Scott McElroy ***@***.***>
Date: Friday, June 30, 2023 at 1:39 PM
To: knossos-project/knossos ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)
Hello,

I’m getting an error message when trying to load my k.zip files that reads “xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 17, column 128”
Do you know if this is an issue with what you mentioned about the data containing no nodes? Or is this a different issue?

Scott

From: Scott McElroy ***@***.***>
Date: Thursday, June 29, 2023 at 5:36 PM
To: knossos-project/knossos ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)
Great, I’ll begin looking at these. Thank you for the help and patience, I really appreciate it!

Scott

From: My-Tien Nguyen ***@***.***>
Date: Thursday, June 29, 2023 at 5:18 PM
To: knossos-project/knossos ***@***.***>
Cc: Scott McElroy ***@***.***>, Author ***@***.***>
Subject: Re: [knossos-project/knossos] .swc file of skeletons is empty (Issue #507)

Yes, almost. This is what I hinted at in my first message: There is no trivial solution for a conversion from segmentation to skeleton because every small bump in the segmentation could in theory be turned into a branch of the skeleton. There are algorithms like skeletonize_3d from scikit-image or maybe you can have a look at https://github.com/seung-lab/kimimaro (haven't worked with it myself yet).

**Comment by my-tien** [comment]
Please file an issue over at https://github.com/knossos-project/knossos_utils for this.
