### ISSUE TITLE
"Scripting" menu item required for Syconn2 but grayed out

### ISSUE THREAD

**Issue by erjel** [knossos-project/knossos#508]
Hi,

I would like to use Knossos for the visualization of a [Syconn2](https://www.nature.com/articles/s41592-022-01624-x) workflow. Unfortunately the "Scriptiong" menu item is grayed out.

Background:
According to the Syconn2 [documentation](https://syconn.readthedocs.io/en/latest/instructions.html#syconn-knossos-viewer) I need the following steps:
1. Analysis results ([download link](https://syconn.readthedocs.io/en/latest/instructions.html#syconn-knossos-viewer) for reference)
2. Start the server with `syconn.server --working_dir=<my results>`
   -  I created the environment with this [conda env file](https://github.com/ada52/SyConn/blob/2e59d9a1c90bd12531c5aac96f6f96ddebdf5e9f/environment.yml) and a following
   - `pip install git+https://github.com/ada52/SyConn.git@2e59d9a1c90bd12531c5aac96f6f96ddebdf5e9f`
3. Download and install the [nightly build](https://github.com/knossos-project/knossos/releases/download/nightly/linux.KNOSSOS.nightly.AppImage) of KNOSSOS
4.  Open the segmentation data in KNOSSOS
5. Add `syconn/kplugin/syconn_knossos_viewer.py` in the *Scripting* menu

Unfortunately, the menu is grayed out .. therefore I cannot proceed ...

Any ideas, why this is the case?

Best wishes and thank you in advance!
Eric

**Comment by erjel** [comment]
Switching to the stable release (version [5.1](https://github.com/knossos-project/knossos/releases/tag/v5.1)) solved this issue for me.

**Comment by Optiligence** [comment]
Hi, the difference might be that v5.1 integrates with python 2.7 whereas the nightly is using python 3.11 at the moment. There might also be other issues that influence if it works. It’s a little more complicated with the regular binary incompatible python 3 releases. 
It should complain on startup though, did it?

**Comment by erjel** [comment]
All I can say that there was no, error message on startup...
