### ISSUE TITLE
Active node pointer is not checked before reference

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#67]
We need to sanitize the usage of active node.
Currently there are several places in the code (namely the annotation widget, e.g. setNodeRadiusAction. but feel free to do a complete survey) where it is referenced without first checked for existence.
An optional "mini-fix" would be to define an active node as soon as a skeleton is loaded, but that's not bullet-proof, in case some annotation code makes it into execution even without a skeleton (as might be the case especially from python).

**Comment by Optiligence** [comment]
If there are nodes, then there’s an activeNode. The pythonapi should sanitize for that i guess (check for existence of nodes before doing operations).
