### ISSUE TITLE
segmentation object LUT

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#71]
pairwise distinguishable nice looking colors pls

**Comment by Optiligence** [comment]
currently, there are 4 black entries in the overlay lut

**Comment by fabiansvara** [comment]
Might be useful: http://tools.medialab.sciences-po.fr/iwanthue/

**Comment by Eroica** [comment]
> Might be useful: http://tools.medialab.sciences-po.fr/iwanthue/

That should be much better than the small palette that I created by hand. (al3xst) Try to use colors from there, and if it's still not suitable, you can try using some colors from here: https://gist.github.com/Eroica/8a6b624a70d21129a218

**Comment by al3xst** [comment]
New/alternative colors where introduced in
https://github.com/knossos-project/knossos/commit/e7186f575d9f328b09aa54a1e3c0c0f7afc3d723
https://github.com/knossos-project/knossos/commit/f8fd6fbd1a543620b609b06640213d896e3700df
