### ISSUE TITLE
Give python shell a proper default width

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#78]
The current one is annoying. Apart from that, I'm surprised how well it works so far ;-).

**Comment by orenshatz** [comment]
I'm not sure if I read the wink correctly.
By proper you mean wider?

**Comment by jmrk84** [comment]
Sorry, should have been more specific. Yes.

**Comment by orenshatz** [comment]
Alright. And by working well, you mean the shell itself, or the thunk to the data structures?

**Comment by jmrk84** [comment]
The shell itself and the usage of external Python libraries that were installed to the Python distribution. But I'll test more.
