### ISSUE TITLE
Non ASCII Windows usernames break task management login

### ISSUE THREAD

**Issue by my-tien** [knossos-project/knossos#82]
One tracer with russian username in windows was not able to log into heidelbrain, because the cookie file could not be created in his local appdata folder.
When creating another user on his pc with an ascii username, he could login and submit without problems.

**Comment by Optiligence** [comment]
@jmrk84 test with 4.1.1 whether heidelbrain integration works and the with master

**Comment by Optiligence** [comment]
nobody tried

**Comment by Optiligence** [comment]
![task login username](https://cloud.githubusercontent.com/assets/1899299/7441590/636e8bdc-f0ee-11e4-9388-d86d11653082.png)
